name = "dr3amy-pages"
main = "worker.js"
compatibility_date = "2024-11-01"

# GitHub OAuth Client ID
# Replace this with your actual GitHub OAuth App Client ID.
[vars]
GITHUB_CLIENT_ID = "Ov23li8Mtz1aLdn2Sh1C"

# Static site assets
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"
